FROM python:3.9-slim
RUN apt update
RUN apt install -y build-essential git
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt
# CMD ["python3", "entrypoint.py"]
CMD ["python3", "-m", "debugpy", "--listen", "0.0.0.0:5688", "src/entrypoint.py"]